@WebApi_HostAddress = http://localhost:5246

### Get Products
GET {{WebApi_HostAddress}}/api/GetProducts
Accept: application/json

### Get Product by ID
GET {{WebApi_HostAddress}}/api/GetProductById?id=2
Accept: application/json

### Add Products
POST {{WebApi_HostAddress}}/api/addproduct
Content-Type: application/json

{
    "name": "New Product"
}

### Add Products 2
POST {{WebApi_HostAddress}}/api/addproduct2
Content-Type: application/json

{
  "name": "New Product"
}

### Add Products With Notification
POST {{WebApi_HostAddress}}/api/addproductwithnotification
Content-Type: application/json

{
  "name": "New Product"
}