@WebApi_HostAddress = http://localhost:5246

### Get Products
GET {{WebApi_HostAddress}}/api/GetProducts
Accept: application/json

### Add Products
POST {{WebApi_HostAddress}}/api/AddProduct
Content-Type: application/json

{
    "Name": "New Product",
    "Id": 100
}